# Generated by Django 4.2.16 on 2024-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
    ]
