# Generated by Django 4.2.16 on 2024-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_limit_one_per_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
